"""Token-usage extraction from agent output messages.

Replaces the previous callback-driven approach (``TokenUsageHandler``) which
was unreliable because LangGraph ``astream_events`` does not guarantee
propagation of ``BaseCallbackHandler`` callbacks passed via ``run_config``.

Instead, after the agent finishes, we parse ``usage_metadata`` /
``response_metadata`` from the AI messages in the returned message list.
This works for both streaming and non-streaming paths.
"""
from __future__ import annotations

from typing import Any


class TokenCounts:
    """Accumulated token usage from agent messages."""

    def __init__(self) -> None:
        self.total_tokens: int = 0
        self.prompt_tokens: int = 0
        self.completion_tokens: int = 0
        self.llm_calls: int = 0

    def __repr__(self) -> str:
        return (
            f"TokenCounts(total={self.total_tokens}, "
            f"prompt={self.prompt_tokens}, "
            f"completion={self.completion_tokens}, "
            f"calls={self.llm_calls})"
        )


def sum_token_usage_from_messages(messages: list[Any]) -> TokenCounts:
    """Sum token usage across all AI messages in a message list.

    Each AI message generated by the LLM carries either:
    - ``response_metadata["token_usage"]`` (from non-streaming ainvoke)
    - ``usage_metadata`` dict (from streaming completion, on some providers)
    """
    counts = TokenCounts()

    for msg in messages:
        msg_type = getattr(msg, "type", None)
        if msg_type != "ai":
            continue

        counted = False

        # Path 1: response_metadata.token_usage (non-streaming ainvoke)
        resp_meta = getattr(msg, "response_metadata", None) or {}
        tu = resp_meta.get("token_usage")
        if isinstance(tu, dict):
            p = int(tu.get("prompt_tokens", 0) or 0)
            c = int(tu.get("completion_tokens", 0) or 0)
            t = int(tu.get("total_tokens", p + c) or 0)
            if t > 0:
                counts.prompt_tokens += p
                counts.completion_tokens += c
                counts.total_tokens += t
                counts.llm_calls += 1
                counted = True

        # Path 2: usage_metadata (streaming, AIMessage.usage_metadata)
        if not counted:
            um = getattr(msg, "usage_metadata", None) or {}
            if um:
                p = int(um.get("input_tokens", 0) or 0)
                c = int(um.get("output_tokens", 0) or 0)
                t = int(um.get("total_tokens", p + c) or 0)
                if t > 0:
                    counts.prompt_tokens += p
                    counts.completion_tokens += c
                    counts.total_tokens += t
                    counts.llm_calls += 1

    return counts


def sum_token_usage_from_llm_result(result: Any) -> TokenCounts:
    """Extract token usage from an LLMResult (legacy on_llm_end event data).

    LLMResult.llm_output["token_usage"] contains:
        prompt_tokens, completion_tokens, total_tokens
    """
    counts = TokenCounts()

    llm_output = getattr(result, "llm_output", None)
    if not isinstance(llm_output, dict):
        return counts

    tu = llm_output.get("token_usage")
    if not isinstance(tu, dict):
        return counts

    p = int(tu.get("prompt_tokens", 0) or 0)
    c = int(tu.get("completion_tokens", 0) or 0)
    t = int(tu.get("total_tokens", p + c) or 0)
    if t > 0:
        counts.prompt_tokens = p
        counts.completion_tokens = c
        counts.total_tokens = t
        counts.llm_calls = 1

    return counts
