apiVersion: v1
kind: Service
metadata:
  name: mind-base-frontend
  namespace: mind-base
  labels:
    app.kubernetes.io/name: mind-base
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mind-base
    app.kubernetes.io/component: frontend
