package service

import "testing"

// Fixture generated by the Python backend's get_device_id (same formula:
// sha256(f"{ua}|{accept_lang}").hexdigest()[:16]) — device fingerprints must
// stay identical across the migration so existing user_device rows match.
func TestDeriveDeviceIDPythonParity(t *testing.T) {
	ua := "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0"
	lang := "zh-CN,zh;q=0.9"
	got := DeriveDeviceID(ua, lang)
	want := "d5dd9b29b147dbc0"
	if got != want {
		t.Fatalf("device_id = %q, want %q", got, want)
	}
}

func TestNormalizeEmail(t *testing.T) {
	cases := []struct {
		in      string
		want    string
		wantErr bool
	}{
		{"User@Example.COM ", "user@example.com", false},
		{"no-at-sign", "", true},
		{"@example.com", "", true},
		{"user@", "", true},
		{"a@b@c.com", "", true},
		{"a@.b.com", "", true},
		{"a@b..com", "", true},
		{"a@b.", "", true},
		{"a b@c.com", "", true},
		{"a@b_c.com", "a@b_c.com", false}, // underscore in domain is legal
	}
	for _, tc := range cases {
		got, err := normalizeEmail(tc.in)
		if tc.wantErr && err == nil {
			t.Fatalf("normalizeEmail(%q): expected error, got %q", tc.in, got)
		}
		if !tc.wantErr && (err != nil || got != tc.want) {
			t.Fatalf("normalizeEmail(%q) = %q, %v; want %q", tc.in, got, err, tc.want)
		}
	}
}

func TestNormalizePhone(t *testing.T) {
	cases := []struct {
		in      string
		want    string
		wantErr bool
	}{
		{"13812345678", "13812345678", false},
		{" 138-1234-5678 ", "13812345678", false},
		{"+8613812345678", "13812345678", false},
		{"008613812345678", "13812345678", false},
		{"12812345678", "", true}, // second digit must be 3-9
		{"1381234567", "", true},  // too short
		{"138123456789", "", true},
	}
	for _, tc := range cases {
		got, err := normalizePhone(tc.in)
		if tc.wantErr && err == nil {
			t.Fatalf("normalizePhone(%q): expected error, got %q", tc.in, got)
		}
		if !tc.wantErr && (err != nil || got != tc.want) {
			t.Fatalf("normalizePhone(%q) = %q, %v; want %q", tc.in, got, err, tc.want)
		}
	}
}

func TestExtractDeviceMeta(t *testing.T) {
	m := ExtractDeviceMeta("Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1")
	if m.DeviceType == nil || *m.DeviceType != "mobile" {
		t.Fatalf("iPhone should parse as mobile, got %v", m.DeviceType)
	}
	if m.OS == nil || *m.OS != "iOS" {
		t.Fatalf("iPhone OS should be iOS, got %v", m.OS)
	}
	if m.Browser == nil || *m.Browser != "Safari" {
		t.Fatalf("browser should be Safari, got %v", m.Browser)
	}

	d := ExtractDeviceMeta("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
	if d.DeviceType == nil || *d.DeviceType != "desktop" {
		t.Fatalf("Windows desktop should parse as desktop, got %v", d.DeviceType)
	}
	if d.OS == nil || *d.OS != "Windows" {
		t.Fatalf("OS should be Windows, got %v", d.OS)
	}
	if d.Browser == nil || *d.Browser != "Chrome" {
		t.Fatalf("browser should be Chrome, got %v", d.Browser)
	}
}

func TestClientIP(t *testing.T) {
	if got := ClientIP("1.2.3.4, 5.6.7.8", "", "9.9.9.9:1234"); got != "1.2.3.4" {
		t.Fatalf("XFF first hop expected, got %q", got)
	}
	if got := ClientIP("", "7.7.7.7", "9.9.9.9:1234"); got != "7.7.7.7" {
		t.Fatalf("X-Real-IP expected, got %q", got)
	}
	if got := ClientIP("", "", "9.9.9.9:1234"); got != "9.9.9.9" {
		t.Fatalf("remote addr expected, got %q", got)
	}
}
