package security

import (
	"strings"
	"testing"
)

// The fixtures below were generated by the Python backend's own
// implementation (app/services/auth/security.py) with key
// "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=". If they stop decrypting,
// the on-disk format has drifted — fix the Go side, never "fix" the test.
const (
	pythonKeyB64   = "MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY="
	pythonCT       = "AAECAwQFBgcICQoLfqDoL51Zhu2FqBTNBeI1vEvulQARjUa4dme/UfqRFwINfUZHgLQlxw=="
	pythonPlain    = "SESSDATA-test-中文-123"
	pythonBcrypt   = "$2b$10$N4.Ta.s0PDjCaMoOUKer2.BCEQT5XmmjGeom/utOf0oS.HfuB/7pe"
	pythonBcryptPw = "S3cret!Password"
)

func TestDecryptPythonAESGCM(t *testing.T) {
	c, err := NewCipher(pythonKeyB64)
	if err != nil {
		t.Fatalf("new cipher: %v", err)
	}
	got, err := c.Decrypt(pythonCT)
	if err != nil {
		t.Fatalf("decrypt python fixture: %v", err)
	}
	if got != pythonPlain {
		t.Fatalf("got %q, want %q", got, pythonPlain)
	}
}

func TestAESRoundtrip(t *testing.T) {
	c, _ := NewCipher(pythonKeyB64)
	ct, err := c.Encrypt(pythonPlain)
	if err != nil {
		t.Fatalf("encrypt: %v", err)
	}
	got, err := c.Decrypt(ct)
	if err != nil || got != pythonPlain {
		t.Fatalf("roundtrip: got %q err %v", got, err)
	}
}

func TestAESDevFallback(t *testing.T) {
	c, err := NewCipher("")
	if err != nil {
		t.Fatalf("new cipher: %v", err)
	}
	if c.Enabled() {
		t.Fatal("empty key must select dev fallback")
	}
	ct, _ := c.Encrypt("hello")
	got, err := c.Decrypt(ct)
	if err != nil || got != "hello" {
		t.Fatalf("dev fallback roundtrip: got %q err %v", got, err)
	}
}

func TestVerifyPythonBcrypt(t *testing.T) {
	if !VerifyPassword(pythonBcryptPw, pythonBcrypt) {
		t.Fatal("go must verify python-generated bcrypt hash")
	}
	if VerifyPassword("wrong", pythonBcrypt) {
		t.Fatal("wrong password must not verify")
	}
}

func TestHashPasswordRoundtrip(t *testing.T) {
	h, err := HashPassword(pythonBcryptPw)
	if err != nil {
		t.Fatalf("hash: %v", err)
	}
	if !VerifyPassword(pythonBcryptPw, h) {
		t.Fatal("self-generated hash must verify")
	}
	if VerifyPassword("wrong", h) {
		t.Fatal("wrong password must not verify")
	}
}

func TestGenerateTokenShape(t *testing.T) {
	tok, err := GenerateToken()
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	// Python secrets.token_urlsafe(48) yields exactly 64 unpadded url-safe
	// base64 chars — the user_tokens.session_token column and the frontend
	// both rely on this shape.
	if len(tok) != 64 {
		t.Fatalf("token length = %d, want 64", len(tok))
	}
	if strings.ContainsAny(tok, "+/=") {
		t.Fatalf("token must be unpadded url-safe base64, got %q", tok)
	}
}

func TestSnowflakeShapeAndMonotonic(t *testing.T) {
	s, err := NewSnowflake(2)
	if err != nil {
		t.Fatalf("new snowflake: %v", err)
	}
	prev := int64(-1)
	seen := make(map[int64]bool, 1000)
	for i := 0; i < 1000; i++ {
		id := s.Next()
		if id <= 0 {
			t.Fatalf("id must be positive, got %d", id)
		}
		if id <= prev {
			t.Fatalf("ids must be monotonic: %d after %d", id, prev)
		}
		if seen[id] {
			t.Fatalf("duplicate id %d", id)
		}
		seen[id] = true
		prev = id
		// worker id must be readable in bits [12,22) — same layout as Python
		if worker := (id >> workerShift) & ((1 << workerBits) - 1); worker != 2 {
			t.Fatalf("worker bits = %d, want 2", worker)
		}
	}
}

func TestSnowflakeInvalidWorker(t *testing.T) {
	if _, err := NewSnowflake(-1); err == nil {
		t.Fatal("negative worker id must be rejected")
	}
	if _, err := NewSnowflake(1024); err == nil {
		t.Fatal("worker id >= 2^10 must be rejected")
	}
}
