package security

import "golang.org/x/crypto/bcrypt"

// HashPassword hashes a plaintext password with bcrypt ($2b$), byte-compatible
// with Python's bcrypt.hashpw — Go's x/crypto/bcrypt verifies Python hashes
// and vice versa.
func HashPassword(password string) (string, error) {
	h, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return "", err
	}
	return string(h), nil
}

// VerifyPassword checks a plaintext password against a stored bcrypt hash.
// Works for hashes generated by either the Python or the Go side.
func VerifyPassword(password, hash string) bool {
	return bcrypt.CompareHashAndPassword([]byte(hash), []byte(password)) == nil
}
