"""
Response schemas — API contract definitions.

Separated from models.py (ORM table mappings) so the interface layer
can evolve independently of the database layer.
"""

from app.response.auth import (
    DeviceInfo,
    QRCodeResponse,
    LoginStatusResponse,
    LoginRequest,
    UserInfoResponse,
    TokenResponse,
    ProfileUpdateRequest,
    ProfileResponse,
    PasswordSetRequest,
    PasswordChangeRequest,
    EmailBindRequest,
    PhoneBindRequest,
    SecurityOverviewResponse,
)
from app.response.chat import (
    WorkspacePage,
    ChatRequest,
    ChatResponse,
    ReasoningStepResponse,
    AgenticChatResponse,
    ChatSessionCreateRequest,
    ChatSessionUpdateRequest,
    ChatSessionResponse,
    ChatSessionListResponse,
    ChatMessageResponse,
    ChatHistoryQueryParams,
    ChatHistoryResponse,
)
from app.response.asr import (
    ASRCreateRequest,
    ASRUpdateRequest,
    ASRReASRRequest,
    ASRContentResponse,
    ASRTaskStatus,
    VideoVersionInfo,
)
from app.response.knowledge import (
    ContentSource,
    VideoInfo,
    VideoContent,
    FavoriteFolderInfo,
    VideoPageInfo,
    VideosResponse,
)
from app.response.quiz import (
    QuestionType,
    QuizGenerateRequest,
    QuizGenerateResponse,
    QuizQuestionResponse,
    QuizSetResponse,
    QuizAnswerItem,
    QuizSubmissionRequest,
    QuizAnswerResult,
    QuizSubmissionResponse,
    QuizHistoryItem,
    QuizHistoryResponse,
    WrongAnswerItem,
    WrongAnswerResponse,
)
from app.response.credentials import (
    CredentialResponse,
    CredentialCreate,
    CredentialUpdate,
    TestResultResponse,
    EmbeddingConfigResponse,
    EmbeddingConfigCreate,
    EmbeddingConfigUpdate,
    ASRConfigResponse,
    ASRConfigCreate,
    ASRConfigUpdate,
    ApiKeyStatusResponse,
    ApiKeySetRequest,
    ProviderUsage,
    CredentialUsageItem,
    UsageSummary,
)
from app.response.favorites import (
    FavoriteFolderResponse,
    FavoriteFolderListResponse,
    FavoriteVideoResponse,
    FavoriteVideoListResponse,
    FavoriteVideoPageResponse,
    SyncFoldersResponse,
    SyncVideosResponse,
    UpdateSelectedResponse,
    DeleteFolderResponse,
    VideoPageItem,
    VideoPageListResponse,
)
from app.response.metadata import (
    VideoMetadataResponse,
    MetadataExtractResponse,
    MetadataUpdateRequest,
)
from app.response.vector import (
    VectorPageStatusResponse,
    VectorPageTaskStatus,
    VectorPageCreateRequest,
    VectorPageReVectorRequest,
)

__all__ = [
    # auth
    "QRCodeResponse",
    "LoginStatusResponse",
    "UserInfoResponse",
    "TokenResponse",
    "ProfileUpdateRequest",
    "ProfileResponse",
    "PasswordSetRequest",
    "PasswordChangeRequest",
    "EmailBindRequest",
    "PhoneBindRequest",
    "SecurityOverviewResponse",
    # chat
    "WorkspacePage",
    "ChatRequest",
    "ChatResponse",
    "ReasoningStepResponse",
    "AgenticChatResponse",
    "ChatSessionCreateRequest",
    "ChatSessionUpdateRequest",
    "ChatSessionResponse",
    "ChatSessionListResponse",
    "ChatMessageResponse",
    "ChatHistoryQueryParams",
    "ChatHistoryResponse",
    # asr
    "ASRCreateRequest",
    "ASRUpdateRequest",
    "ASRReASRRequest",
    "ASRContentResponse",
    "ASRTaskStatus",
    "VideoVersionInfo",
    # knowledge
    "ContentSource",
    "VideoInfo",
    "VideoContent",
    "FavoriteFolderInfo",
    "VideoPageInfo",
    "VideosResponse",
    # quiz
    "QuestionType",
    "QuizGenerateRequest",
    "QuizGenerateResponse",
    "QuizQuestionResponse",
    "QuizSetResponse",
    "QuizAnswerItem",
    "QuizSubmissionRequest",
    "QuizAnswerResult",
    "QuizSubmissionResponse",
    "QuizHistoryItem",
    "QuizHistoryResponse",
    "WrongAnswerItem",
    "WrongAnswerResponse",
    # credentials
    "CredentialResponse",
    "CredentialCreate",
    "CredentialUpdate",
    "EmbeddingConfigResponse",
    "EmbeddingConfigCreate",
    "EmbeddingConfigUpdate",
    "ASRConfigResponse",
    "ASRConfigCreate",
    "ASRConfigUpdate",
    "ApiKeyStatusResponse",
    "ApiKeySetRequest",
    "ProviderUsage",
    "CredentialUsageItem",
    "UsageSummary",
    # favorites
    "FavoriteFolderResponse",
    "FavoriteFolderListResponse",
    "FavoriteVideoResponse",
    "FavoriteVideoListResponse",
    "FavoriteVideoPageResponse",
    "SyncFoldersResponse",
    "SyncVideosResponse",
    "UpdateSelectedResponse",
    "DeleteFolderResponse",
    "VideoPageItem",
    "VideoPageListResponse",
    # metadata
    "VideoMetadataResponse",
    "MetadataExtractResponse",
    "MetadataUpdateRequest",
    # vector
    "VectorPageStatusResponse",
    "VectorPageTaskStatus",
    "VectorPageCreateRequest",
    "VectorPageReVectorRequest",
]
